@startuml Domain
skinparam style strictuml
skinparam DefaultFontName Arial
skinparam DefaultFontSize 16
skinparam DefaultFontStyle bold
skinparam ArrowThickness 2.2
skinparam ArrowColor #gray
hide empty members


class "Builting" as building {
string: id
string: name
}

class "Floor" as floor {
int: number
get_area()

}

class "Room" as room {
string: name
float: area
}

class "Device" as device {
string: id
string: manufacturer
string: model
sting: deviceType
string: nickName
}

class "Sensor" as sensor {
lastMeasurement()
historicalMeasurement()
}

Class "Actuators" as actuator {
getState() : State
setState(State)
}

Class "Measurement" as meas {
DataeTime : timestamp
float : value
string : unit
}

Class "State" as state {
bool : isOn
float : targetTemperature
int : dimLevel
}


building "1" *-- "1..*" floor : Contains

floor "1" *-- "1..*" room  : Contains

room "1" *-- "1..*" device : Contains

room "1" <--  device : Located in

device  <--  sensor 

device  <--  actuator 

sensor "1" *-- "0..*" meas : Produces

actuator "1" *-- "0..1" state : Sets



@enduml